apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-ruting
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  liveness:
    path: /isalive
  readiness:
    path: /isready
  kafka:
    pool: "{{ kafka.pool }}"
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  secureLogs:
    enabled: true
