package no.nav.dagpenger.ruting

interface SkjemaType {
    val skjemakode: String
    val navn: String
}

enum class SkjemaTypeEnum(override val skjemakode: String) : SkjemaType {
    DAGPENGESØKNAD_ORDINÆR("NAV 04-01.03"),
    DAGPENGESØKNAD_ORDINÆR_ETTERSENDING("NAVe 04-01.03"),
    DAGPENGESØKNAD_PERMITTERT("NAV 04-01.04"),
    DAGPENGESØKNAD_PERMITTERT_ETTERSENDING("NAVe 04-01.04"),
    DAGPENGESØKNAD_GJENOPPTAK_ORDINÆR("NAV 04-16.03"),
    DAGPENGESØKNAD_GJENOPPTAK_ORDINÆR_ETTERSENDING("NAVe 04-16.03"),
    DAGPENGESØKNAD_GJENOPPTAK_PERMITTERT("NAV 04-16.04"),
    DAGPENGESØKNAD_GJENOPPTAK_PERMITTERT_ETTERSENDING("NAVe 04-16.04"),
    DAGPENGESØKNAD_UTDANNING("NAV 04-06.05"),
    DAGPENGESØKNAD_ETABLERING("NAV 04-06.08"),
    KLAGE_ELLER_ANKE("NAV 90-00.08"),
    KLAGE("NAV 90-00.08 K"),
    KLAGE_ETTERSENDING("NAVe 90-00.08 K"),
    ANKE("NAV 90-00.08 A"),
    ANKE_ETTERSENDING("NAVe 90-00.08 A"),
    GENERELL("GENERELL_INNSENDING"),
    DOKUMENTASJON_ANDRE_YTELSER("K1"),
    TIMELISTER("M6"),
    BREV_FRA_BOBESTYRER_KONKURSFORVALTER("M7"),
    KOPI_AV_SØKNAD("N2"),
    KOPI_AV_UNDERSØKELSESRESULTAT("N5"),
    SØKNAD_OM_UTSTEDELSE_AV_ATTEST_PD_U2("NAV 04-02.01"),
    BEKREFTELSE_PÅ_ANSETTELSESFORHOLD("NAV 04-02.03"),
    SØKNAD_OM_ATTEST_PD_U1_N_301_TIL_BRUK_VED_OVERFØRING_AV_DAGPENGERETTIGHETER("NAV 04-02.05"),
    EGENERKLÆRING_OVERDRAGELSE_AV_LØNNSKRAV("NAV 04-03.07"),
    OVERSIKT_OVER_ARBEIDSTIMER("NAV 04-03.08"),
    BEKREFTELSE_PÅ_SLUTTÅRSAK_NEDSATT_ARBEIDSTID_IKKE_PERMITTERT("NAV 04-08.03"),
    BEKREFTELSE_PÅ_ARBEIDSFORHOLD_OG_PERMITTERING("NAV 04-08.04"),
    EGENERKLÆRING_FASTSETTELSE_AV_GRENSEARBEIDERSTATUS("NAV 04-13.01"),
    ETTERSENDELSE_TIL_SØKNAD_OM_ATTEST_PD_U2("NAVe 04-02.01"),
    ETTERSENDELSE_TIL_SØKNAD_OM_ATTEST_PD_U1_N_301_TIL_BRUK_VED_OVERFØRING_AV_DAGPENGERETTIGHETER("NAVe 04-02.05"),
    ETTERSENDELSE_TIL_EGENERKLÆRING_OVERDRAGELSE_AV_LØNNSKRAV_VED_KONKURS("NAVe 04-03.07"),
    ETTERSENDELSE_TIL_OVERSIKT_OVER_ARBEIDSTIMER("NAVe 04-03.08"),
    ETTERSENDELSE_TIL_BEKREFTELSE_PÅ_SLUTTÅRSAK_NEDSATT_ARBEIDSTID_IKKE_PERMITTERT("NAVe 04-08.03"),
    ETTERSENDELSE_TIL_BEKREFTELSE_PÅ_ARBEIDSFORHOLD_OG_PERMITTERING("NAVe 04-08.04"),
    ARBEIDSAVTALE("O2"),
    BEKREFTELSE_FRA_STUDIESTED_SKOLE("O9"),
    DOKUMENTASJON_AV_SLUTTÅRSAK("S6"),
    KOPI_AV_ARBEIDSAVTALE_SLUTTÅRSAK("S7"),
    SJØFARTSBOK_HYREAVREGNING("S8"),
    ELEVDOKUMENTASJON_FRA_LÆRESTED("T1"),
    DOKUMENTASJON_AV_SLUTTDATO("T2"),
    TJENESTEBEVIS("T3"),
    OPPHOLDS_OG_ARBEIDSTILLATELSE_ELLER_REGISTRERINGSBEVIS_FOR_EØS_BORGERE("T4"),
    SED_U006_FAMILIEINFORMASJON("T5"),
    PERMITTERINGSVARSEL("T6"),
    DOKUMENTASJON_AV_ARBEIDSFORHOLD("T8"),
    DOKUMENTASJON_AV_HELSE_OG_FUNKSJONSNIVÅ("T9"),
    U1_PERIODER_AV_BETYDNING_FOR_RETTEN_TIL_DAGPENGER("U1"),
    KOPI_AV_SLUTTAVTALE("V6"),
    FØDSELATTEST_BOSTEDSBEVIS_FOR_BARN_UNDER_18_ÅR("X8"),
    UTTALELSE_ELLER_VURDERING_FRA_KOMPETENT_FAGPERSONELL("XY"),
    MELDEKORT("NAV 00-10.02"),
    ;

    data class UkjentSkjemaKode(override val skjemakode: String) : SkjemaType {
        override val navn: String = "Ukjent"
    }

    override val navn: String = this.name

    companion object {
        fun String.tilSkjemaType(): SkjemaType {
            return entries.firstOrNull { it.skjemakode == this }
                ?: UkjentSkjemaKode(this)
        }
    }
}
